<?php

if (!defined('BASEPATH')) die("\nDon't forget the bootstrap!!\n\n");

require_once BASEPATH.'/includes/PHPDS_core.class.php';




/**
 * Test class for PHPDS_controller.
 * Generated by PHPUnit on 2011-08-09 at 01:06:29.
 */
class PHPDS_coreTest extends PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        $PHPDS = TEST_main::instance();
        $this->object = $PHPDS->_factory('PHPDS_core');

        $this->object->construct();
    }

    /**
     * This call is deprecated
     */
    function testsafeName()
    {
        /* @var PHPDS_core $core */
        $core = $this->object;

        $this->assertEquals('a-b-c-d-e-f-g-h', $core->safeName('A--B C/D"E%F\\G\'H'));
        $this->assertEquals('abcdefgh', $core->safeName('A--B C/D"E%F\\G\'H', ''));
        $this->assertEquals('a.b.c.d.e.f.g.h', $core->safeName('A--B C/D"E%F\\G\'H', '.'));
        $this->assertFalse($core->safeName(''));
        $this->assertEquals('-', $core->safeName('--'));
    }

    /**
     * This call is deprecated
     */
    function testrightTrim()
    {
        /* @var PHPDS_core $core */
        $core = $this->object;

        $this->assertEquals('ab', $core->rightTrim('abcd', 'cd'));
        $this->assertEquals('abcd', $core->rightTrim('abcd ', 'cd'));
        $this->assertEquals('abcd', $core->rightTrim('abcd', 'c'));
    }


    /**
     * TO BE DONE
     *
     */
    function test_webPath()
    {
        $pds = TEST_main::instance();
        $core = $pds->PHPDS_core();
        $template = $pds->PHPDS_template();

        $template->CDN = 'http://www.cdn.test/';

        // webPath($relativePath, $useCDN)
        $this->assertEquals('/plugins/PHPDevShell/public/test.js', $core->webPath('public/test.js'));
        $this->assertEquals('/plugins/PHPDevShell/public/test.js', $core->webPath('public/test.js', false));
        $this->assertEquals('http://www.cdn.test//plugins/PHPDevShell/public/test.js', $core->webPath('public/test.js', true));


        // webPath(array($pluginName, $relativePath), $useCDN)

        $plugins = & $pds->PHPDS_db()->pluginsInstalled;

        $plugins['DummyPlugin'] = array(
            'plugin_folder' => 'Dummy_Plugin',
            'status'        => 'install',
            'version'       => 1000,
            'use_logo'      => 0
        );

        $this->assertEquals('/plugins/Dummy_Plugin/public/test.js', $core->webPath(array('DummyPlugin', 'public/test.js')));
        $this->assertEquals('/plugins/Dummy_Plugin/public/test.js', $core->webPath(array('DummyPlugin', 'public/test.js'), false));
        $this->assertEquals('http://www.cdn.test//plugins/Dummy_Plugin/public/test.js', $core->webPath(array('DummyPlugin', 'public/test.js'), true));
        $this->assertEquals(false, $core->webPath(array('DummyErrorPlugin', 'public/test.js')));


        // webPath('http://complete.url/path')

        $this->assertEquals('http://complete.url/path', $core->webPath('http://complete.url/path'));
        $this->assertEquals('http://complete.url/path', $core->webPath('http://complete.url/path'), false);
        $this->assertEquals('http://complete.url/path', $core->webPath('http://complete.url/path'), true);
    }
}