<?php




if (!defined('BASEPATH')) die("\nDon't forget the bootstrap!!\n\n");

require_once BASEPATH . '/includes/models/PHPDS_user.query.php';


/**
 * Test class for PHPDS_array.
 * Generated by PHPUnit on 2011-07-25 at 11:26:16.
 */
class PHPDS_arrayTest extends PHPUnit_Framework_TestCase
{


	/**
	 * @var PHPDS_array
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new PHPDS_array;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	public function testSet()
	{
		$this->object->__set('a', 'A');
		
		$this->assertEquals('A', $this->object['a']);
	}

	public function testGetDefined()
	{
		$this->object['b'] = 'B';
		
		$this->assertEquals('B', $this->object['b']);
	}

	/*public function testGetunefined()
	{
		// this feature has been removed
		$this->assertNull($this->object['c']);
	}*/


}

?>
